### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by thphao** [flyingsparx/WekaPy#2]
I run examples load_test_model_example.py use classifiers.functions.MultilayerPerceptron

ERROR

Traceback (most recent call last):
  File "load_test_model_example.py", line 32, in <module>
    model.test(model_file="wekapy_data/models/model.model")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wekapy/Model.py", line 150, in test
    process_output, self.time_taken = run_process(options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/wekapy/Helpers.py", line 17, in run_process
    raise WekaPyException(line.split(' ', 1)[1])
wekapy.WekaPyException.WekaPyException: Could not find or load main class weka.classifiers.functions.MultilayerPerceptron

**Comment by ipaulbogdan** [comment]
I have the some problem. Do I need to download them?

**Comment by willwebberley** [comment]
Hi,

Apologies for the delay in reply.

Please ensure that the WEKA JAR file is stored locally somewhere, and that its directory is added to your Java `CLASSPATH` (https://docs.oracle.com/javase/tutorial/essential/environment/paths.html).

Once done, please try testing one of the examples again to make sure they run correctly. Does this help address your issue?

**Comment by SinaiAranda** [comment]
```
$export CLASSPATH=/home/your_dir/weka-3-9-3/weka.jar
$echo ${CLASSPATH}
$python3 testwekapy.py 
```
